### PR TITLE
chore: bump from 3.19.0 to 3.20.1

### PR DESCRIPTION
**Pull request by Sanix-Darker**
## Change Summary

- Bump toucan-connectors

## Checklist

* [ ] Unit tests for the changes exist
* [ ] Tests pass on CI and coverage remains at 100%
* [ ] Documentation reflects the changes where applicable

### CODE REVIEW

**Comment by lukapeschke** [comment]
I'd consider this to be 3.19.1 since it's only a fix

**Comment by Sanix-Darker** [comment]
> I'd consider this to be 3.19.1 since it's only a fix

Already pushed on https://pypi.org/project/toucan-connectors/ 😞

**Comment by lukapeschke** [comment]
... meaning the release has been built from a commit that's not on master ??

**Comment by Sanix-Darker** [comment]
> ... meaning the release has been built from a commit that's not on master ??

From this branch yes !
my bad, i should have waited for the merge !

**Comment by lukapeschke** [comment]
That must never happen! As a user, how can I trust a library with version from commits that are not on the main branch ? How can I be sure that the wheel is not malicious ? I'll approve this one because it's too late, and if we rebase it should work (except the timestamsp will be wrong), but the right thing to do would be to yank the release from PyPI, delete the github release, mark this as 20.0.1 and do a proper release **after the bump commit has been merge into the main branch**

**Review by lukapeschke — APPROVED** [review]

**Comment by Sanix-Darker** [comment]
👍🏽
- pypi release was yanked!
- GitHub release was deleted!

After the CI goes green I will create those again from the 3.20.1 version !

**Pull request merged**
