### PR TITLE
Redshift connector does not work with ConnectionManager

### PR DESCRIPTION
**Pull request by jGundermann**
## Change Summary

Removing connection manager how was responsible for some weird hanging connections.

## Checklist

* [x] Unit tests for the changes exist
* [ ] Tests pass on CI and coverage remains at 100%
* [x] Documentation reflects the changes where applicable

### CODE REVIEW

**Comment by Sanix-Darker** [comment]
Thanks for this PR 🔥 !
Do we have a running guru instance to validate this for a bump ?

**Comment by jGundermann** [comment]
@Sanix-Darker : not now. I will do it asap

@raphaelvignes : When creating a long lived connection it seems that there where conflicts inside of redshift temporary tables. It seems that they try to recreate them and this raised a error on the connection.

**Review by raphaelvignes — APPROVED** [review]
OK for me modulo a quick test on a guru. 
Thx!

**Review by lukapeschke — APPROVED** [review]

**Comment by jGundermann** [comment]
> 
did you had a chance to have a look into the guru @raphaelvignes ?

**Comment by raphaelvignes** [comment]
@jGundermann good4me, we can merge :)

**Pull request merged**
