### PR TITLE
Google Sheets: retrieve unformatted values instead of formatted ones

### PR DESCRIPTION
**Pull request by raphaelvignes**
## Change Summary

By default google sheets applies the decimal separator defined in the gsheet locale. 
We want values such as "," to be correctly interpreted so we added the parameter valueRenderOption=UNFORMATTED_VALUE' to the URL used to retrieve data in the connector

## Checklist

* [x] Unit tests for the changes exist
* [x] Tests pass on CI and coverage remains at 100%
* [x] Documentation reflects the changes where applicable

### CODE REVIEW

**Comment by testinnplayin** [comment]
[(8) EPIC ETQC, je ne vois pas des propriétés privées dans le formulaire d'édition du connecteur GoogleSheets2](https://trello.com/c/woTQo3Fh/850-8-epic-etqc-je-ne-vois-pas-des-propri%C3%A9t%C3%A9s-priv%C3%A9es-dans-le-formulaire-d%C3%A9dition-du-connecteur-googlesheets2)

**Review by davinov — CHANGES_REQUESTED** [review]
Thanks and congrats for this first PR!
Looking at the diff, it seems that a lot of other commits, unrelated to your PR, are included.
Could you rebase this PR in order to only keep the relevant commits, please?

**Comment by raphaelvignes** [comment]
I restarted from master and pushed only my changes to this branch.

**Review by davinov — APPROVED** [review]
:checkered_flag: Thanks!

**Comment by raphaelvignes** [comment]
Closing as the code was integrated elsewhere

**Pull request closed without merging**
